
@url_dev = http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 341c3aae93f727e6a85bfdbdc285feca12e62a3e96bbdda4c15bd8147d73bc5f162b65e4cd88f8ce9bd6c6091bbe35692855330c94669b39e7b0f9cbf065e697

{
    "name": "Shop TIPS 1",
    "email": "shoptips35@gmail.com",
    "password": "abc123"
}
 
### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 341c3aae93f727e6a85bfdbdc285feca12e62a3e96bbdda4c15bd8147d73bc5f162b65e4cd88f8ce9bd6c6091bbe35692855330c94669b39e7b0f9cbf065e697

{
    "email": "shoptips32@gmail.com",
    "password": "abc123"
}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 341c3aae93f727e6a85bfdbdc285feca12e62a3e96bbdda4c15bd8147d73bc5f162b65e4cd88f8ce9bd6c6091bbe35692855330c94669b39e7b0f9cbf065e697
x-client-id: 663dbff8f63a05deaddd79fb
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNjYzkzNDA2NzcxZjc5MTgyYzlkNzIiLCJlbWFpbCI6InNob3B0aXBzMzJAZ21haWwuY29tIiwiaWF0IjoxNzE1NTczNTczLCJleHAiOjE3MTU3NDYzNzN9.aKi8C1yEl0qlFGLeKJeKx_pP1_knDt4hx5FrXRkrUoFD02gRT5Ph0r0Rpfv2sJKW04JR2Mg0O_-GPxfPL5hOo0T9_xNbNADtB57UfysAqrcFqv3xwHG8Yw3vRv2jk2Uvsw_1Zurjcx2XNc5ipn7yFwvOkD2fX-uSeKMc01vaxAmAM19LGPgvSa3RycfVzL6Qd4I28fSrY2JyjAbGktJWASwtTa8aiFOYNas6TKnwP97VKPhvr2IErEFcnH4_ouQ4Pa65Dx3DEU0JU57XQuBmzO_eaoUBjUvFHPYbhdoA9nRvqYLx2_n0H2cfRyBrpjaXctuuCcjrE0GKBuA-EkhhHJQwVzgB3W7li_FmH_fnKIfsnwcgchIV3j-p8ZD3IXDBU3ZPKdlpJITjkl33oXw3_r_0-tiBapeiqNBG_yntjCUJnlD17BV6kN5tuYFmoijOWMFuLyjmTWj9H759HEJy30OUIsLLDCpiWXGgIARMgZoLldcNISuKfG6Wy7KXeThNPGipY11Tia508Iay4c6L91iEkneSrB60cZzqK1z8BEosKMPCqRE_X5JE9BsLjXuaEv8wZVlc5p2kAsoPKpr_qhhVsD09lPxF2zrng5cuOPVHPl8zudy_OiMKeavwvMZMsp9baEDL_teuW1f9Io_-RY7y3ymqCsR4Wwl7U_fXAvo

{
    "email": "shoptips32@gmail.com",
    "password": "abc123"
}


### handlerRefreshToken
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: 341c3aae93f727e6a85bfdbdc285feca12e62a3e96bbdda4c15bd8147d73bc5f162b65e4cd88f8ce9bd6c6091bbe35692855330c94669b39e7b0f9cbf065e697
x-client-id: 663cc93406771f79182c9d72
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNjYzkzNDA2NzcxZjc5MTgyYzlkNzIiLCJlbWFpbCI6InNob3B0aXBzMzJAZ21haWwuY29tIiwiaWF0IjoxNzE1NTczOTg3LCJleHAiOjE3MTU3NDY3ODd9.a-tM9zvZuFMajnbAAG8Yk5MXsW4ONLpN7ZpY_7mGJwd19Wkm5-QcnhCvn8I1tCkE3-Qd3JpnteGiByxMA2i3n6q4LRWGHFV20KQ7y6C7NijsYz28MSm2jUYEZeZBBDQof6ZqzQh4CmBefLa0ijmbsZ3ucNYmtWUgR-oLtzD8fHV-NebhHsYhljVuiFZQIiP9g_C0iVbHSmxO_Fg9u9TAYZGjOLb712yzNf_gowGbKYlwxl4NO61s7Zw2FDzsEHtLwVhHL0mRZzliL-1oBrVNaMa2IholjDDxy8bPG6GwqbNqluMQmQmAkyiQvKx4QRw42e5JRUybhM_IOeAE1KP9g9sYuxwBvyAnjX0_gU_rcBoai8uCi-DJyHD2BPh2S-oG0dRiZzx7QoX6Itu21LYycCUud9HKnvLkCU9Ri3jROouzlO_mNRQPG-cXWD14CvBDlhAfCbryEmFNVCFMQhb53Q95udykHQ6MbCXbUk4FOeV6i5AQyn_kQ7to-qB08tSV_Xs8oCko6kPb8ezzLvKyeUz9FiH3O6jXTOopGPfm7b-ugPbBvIJY__TYp4sGqDX6AlhgciC2xqWUZpfSrg1x0USv5xZ0EHFSHLDS_oeq9cAeflfo4JE6ExQrTxzHTI9UhJcls6wvnF47KK90c7qSxs70iKhTsDTibo49oad20Ag

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjNjYzkzNDA2NzcxZjc5MTgyYzlkNzIiLCJlbWFpbCI6InNob3B0aXBzMzJAZ21haWwuY29tIiwiaWF0IjoxNzE1NTczOTU0LCJleHAiOjE3MTU3NDY3NTR9.SRUuTIcz6jrB5Sm4U7PY0gjDib3-5RxAkV8EY435h8vffscUuUvvnoZiknMgLsdNf1kbsMYqOiuZ9Fnx27HD6tKQv6xHiFsLTGhLp0RinQcUz8oix3Q6T6CRZ27BmM6SGXKvNpztB_9xCahTanJ5MnES3_Faua5ssb6Yu0_4YDJiF_Z5N9oKhOIteCRiXzjx_9zUnaruhMSdWhHhExCo_HmwonSgP3Kzi03TbE3CL8OKBfmp41L2_zOjHxqCWfP-NuDSRGKv9gcFUPr4GLkIX3hJ6vjXh26FryHKSRsiWdIov1053VMsZn4qA97L0ZbacQ2Iq8xVKnrJlNmHkGK00_NSG0_NPw49zbXF7W0zv6JKReURXKA-qmgy7IyOEJhSbGV5lN4XwNVo5oD2iBxzi1l2jRO4wFs5j-oq75oSJW1bKbSJVPOBBRnCDkxFTZGeTR3LcS_USqv42F56BwmoltiZabzWXytivc236vsd3KAHGKPIfalHNSM6sP0JeJ_bMTXNa0XeA4gGLYwD-JTZVwxeyLPadMuovT_a3qWtGzAyQxK1dasyHmhcnSHBg2VMdBr1ytpOHI77mnO1tcrw7vHn8jCnH_cfhp8DWOgnEQZ1rBiVARvAxxZwvGMBhAydGX3DvTPxhGbPnWTgf_lFLv-O-yEYdDAMpxBqhlrq_lY"}
